# Generated by Django 4.2.7 on 2023-11-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_date']},
        ),
        migrations.AddField(
            model_name='message',
            name='file_content',
            field=models.FileField(blank=True, null=True, upload_to='static/files/'),
        ),
        migrations.AddField(
            model_name='message',
            name='what_is_it',
            field=models.TextField(blank=True, null=True),
        ),
    ]
