# Generated by Django 4.2.7 on 2023-11-17 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file_content',
        ),
    ]
